### ISSUE TITLE
Strange behavior with pagination

### ISSUE THREAD

**Issue by Darknico** [dragomano/Warehouse#4]
**Describe the bug** (**Опишите баг**) The pagination not work correctly

**To Reproduce** (**Как воспроизвести, по шагам**) Steps to reproduce the behavior:
    1. Set "Number of boxes per page (for pagination)", for example 1 box for page
![immagine](https://github.com/dragomano/Warehouse/assets/3503100/1c2ca640-e379-4443-8b9d-8b106d754686)

    2. In my case, the rack contains 6 file
![immagine](https://github.com/dragomano/Warehouse/assets/3503100/a598e6ee-a50d-4acb-9c57-412bc30151a0)

    3. in the rack, view the pagination
![immagine](https://github.com/dragomano/Warehouse/assets/3503100/34244924-02be-43c0-bc6a-2ae175baad7f)
21 pages?  wow =D

This is one of more strange behavior, if set different pagination, non work correclty.

**Environment**
    * Version/Git revision: 0.1
    * Database Type: MySQL
    * Database Version: 5.7.28
    * PHP Version: 8.1.1
    * SMF Version: 2.1.4

**Comment by Darknico** [comment]
I tested the PR, not work correctly.
The pagination is ok, but not show the correct boxes

**Comment by dragomano** [comment]
Do you mean number of boxes?

**Comment by Darknico** [comment]
no, the content.
for example: 

rack contains 6 boxes, set the pagination 10, show only 2 boxes in the single page
or
rack contains 6 boxes, set the pagination 6, show only one box in each page.. the same box
etc...

**Comment by dragomano** [comment]
Ok, I've added more fixes

**Comment by Darknico** [comment]
ok, tested and work correclty 👍🏻
